# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fault_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(max_length=200)),
                ('point', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=200)),
                ('fault_type', models.CharField(max_length=32)),
                ('info', models.TextField()),
                ('method', models.TextField()),
                ('deal_ID', models.IntegerField()),
            ],
        ),
    ]
