# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faults_record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault_info',
            name='deal_ID',
        ),
        migrations.AddField(
            model_name='fault_info',
            name='deal_chinese_name',
            field=models.CharField(default=datetime.datetime(2016, 10, 8, 6, 26, 59, 995000, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
    ]
