# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults_record', '0004_auto_20161008_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault_info',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 8, 14, 45, 2, 338000)),
        ),
    ]
