# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 07:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faults_record', '0008_auto_20161008_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault_info',
            name='fault_device',
            field=models.CharField(default=datetime.datetime(2016, 10, 8, 7, 35, 32, 995000, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
