# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults_record', '0009_fault_info_fault_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=64)),
            ],
        ),
    ]
