# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 06:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(default=datetime.datetime(2016, 7, 26, 6, 25, 50, 810000, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
    ]
