# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 02:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160726_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chinese_name',
            field=models.CharField(default=datetime.datetime(2016, 7, 27, 2, 3, 9, 862000, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
    ]
