# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_user_chinese_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.CharField(default=datetime.datetime(2016, 7, 27, 8, 33, 20, 875000, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
    ]
