# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_user_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pingjia',
            field=models.CharField(default=datetime.datetime(2016, 7, 28, 2, 16, 22, 525000, tzinfo=utc), max_length=4),
            preserve_default=False,
        ),
    ]
