# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 07:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_task_pingjia'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createUserGroup',
            field=models.CharField(default=datetime.datetime(2016, 7, 28, 7, 49, 3, 247000, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
    ]
