# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 03:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_info',
            name='create_date',
            field=models.CharField(default=datetime.datetime(2016, 10, 9, 3, 24, 15, 690000, tzinfo=utc), max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device_info',
            name='point',
            field=models.CharField(default=datetime.datetime(2016, 10, 9, 3, 24, 37, 864000, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device_info',
            name='create_user',
            field=models.CharField(max_length=64),
        ),
    ]
