# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0002_auto_20161009_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_info',
            name='cpu',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device_info',
            name='nic',
            field=models.CharField(default=datetime.datetime(2016, 10, 9, 7, 24, 9, 272000, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device_info',
            name='ram',
            field=models.CharField(default=datetime.datetime(2016, 10, 9, 7, 24, 23, 493000, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device_info',
            name='storage',
            field=models.CharField(default=datetime.datetime(2016, 10, 9, 7, 24, 38, 797000, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
    ]
